### ISSUE TITLE
Decompression issue

### ISSUE THREAD

**Issue by GrounderGithub** [SolatoroboHacking/CCBUtils#2]
Prefacing this by saying that the majority of the time, this program works as intended, and also that I am using release 0.3.  With that out of the way, there seems that some CCB files use a different compression method than expected, and as such the files contained within do not export in a workable form.

A few examples, they all seem to use the same method:
s2air06bkg00.ccb
nc20dms20.ccb
sdcmn21.ccb

Unclear if this is a third method or not:
s2air04bkg00.ccb

**Comment by SolatoroboHacking** [comment]
My apologies for not getting to you sooner. Apparently Solatorobo uses both LZ10 and LZ11 compression! I did not realize this since it appears to only be on a few files. I am working on implementing LZ10 support now in both the Extractor and Compressor, so you should be able to both extract and modify these files soon. I will update and close this issue as soon as that is done and I will publish a new release.

Out of curiosity, if I may ask, since you are the first person I've seen who is actually experimenting with these, what are you using my tools for? I'd love to hear more about it!

**Comment by SolatoroboHacking** [comment]
Update: I have a working version of the extractor, I will post it soon after I get the constructor working.

**Comment by SolatoroboHacking** [comment]
Update 2: Just got the Constructor working with LZ10. A new release and updated source files will be posted tomorrow morning. Will close issue when done

**Comment by GrounderGithub** [comment]
> Out of curiosity, if I may ask, since you are the first person I've seen who is actually experimenting with these, what are you using my tools for? I'd love to hear more about it!

vg-resource ripping, which i am currently breaking from!

**Comment by SolatoroboHacking** [comment]
Oh cool!! I'm sorry, I've been super busy, but tonight I will get the new
release and code up for LZ10 so that you can continue!

Best of luck to you on your work!

**Comment by SolatoroboHacking** [comment]
@GrounderGithub I finally finished getting the new release published. Sorry it took so long.

Glad you're enjoying my work! Thank you!
